name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message:
            '**Note:** Design changes (such as introducing a new UI or updating
            an existing UI) require approval from the design team. @gjimish'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
