name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  post-ui-approval-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: UI Change Approval
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            **Note:** UI changes (such as introducing a new UI or updating an existing UI) require approval from the FRONTEND team. @gjimish

  post-design-approval-comment:
    if: contains(github.event.pull_request.title, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Design Approval
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            **Note:** require approval from the design team. @gjimish
